# Generated by Django 2.0.2 on 2019-08-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperature',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
